name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.0]
        experimental: [false]
        include:
          - php: 8.0
            analysis: true
          - php: 8.1
            experimental: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions